overrides:
  ceph:
    conf:
      global:
        lockdep: true
    log-ignorelist:
      - missing required features
      - \(MDS_CACHE_OVERSIZED\)
      - \(MDS_TRIM\)
      - \(MDS_CLIENTS_BROKEN_ROOTSQUASH\)
      - report clients with broken root_squash implementation
tasks:
  - cephfs_test_runner:
      fail_on_skip: false
      modules:
        - tasks.cephfs.test_admin.TestFsAuthorize.test_multifs_single_path_rootsquash
